# Generated by Django 4.1.5 on 2023-01-16 18:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import (
    migrations,
    models
)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TgUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_chat_id', models.BigIntegerField(unique=True, verbose_name='Chat ID')),
                ('tg_user_id', models.BigIntegerField(unique=True, verbose_name='Tg User ID')),
                ('tg_username', models.CharField(blank=True, default=None, max_length=32, null=True, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Tg Username')),
                ('verification_code', models.CharField(max_length=10, unique=True, verbose_name='Код подтверждения')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Телеграм пользователь',
                'verbose_name_plural': 'Телеграм пользователи',
            },
        ),
    ]
