# Generated by Django 4.1.5 on 2023-01-15 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_add_bot_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tguser',
            options={'verbose_name': 'Telegram пользователь', 'verbose_name_plural': 'Telegram пользователи'},
        ),
    ]
