# Generated by Django 4.1.5 on 2023-01-15 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_alter_tguser_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tguser',
            old_name='tg_username',
            new_name='username',
        ),
    ]
